### ISSUE TITLE
[2.2] Update color attributes

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#22]
Color attribute ( already existed in magento ) , needs to be used with our configurable product and populated with values .
And then populate more products with the new values .

Quote from John 

> The "primary colour" only exists to allow filtering in searches to work more easily (e.g. you may have products with colours of "Vibrant White" & "Off-White", but when a customer is searching for a white t-shirt, they expect just to choose "white" in search filter and see all products with any "white"-like colour).

**Comment by babanesma** [comment]
The main functionality is looking good , but when I try to search for a the color in the website , it is loading everything . 

This url ( http://tee-shop.local/catalogsearch/result/?q=pure+brown+shirt ) should load pure brown shirts only , but it is loading all shirts

**Comment by ahmedReda1** [comment]
@babanesma  
That's because of the search technique we are using combined( like and full text )
1- like : is getting a query for each word you searching for 
2- full text : to get a specific product you need enter the full name ex:'T-shirt_Dark_Blue_L'
3- combined : is using them both (the best)

*\* you had to search for 'pure_brown' instead of 'pure brown shirt' 
to get only 5 sizes of pure brown shirts 

so we have 2 solutions 
1- make new color attribute filterable like primary colour
2- make all associated shirts invisible and add them to Base Conf

**Comment by babanesma** [comment]
Closed by mistake

**Comment by babanesma** [comment]
opening a new issue to fix search issue #24
