### ISSUE TITLE
[2.1] Setup Jenkins CI Deploy

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#6]
Create new Jenkins job to automatically deploy Tee Shop to dev when a commit is pushed. Add scripts to ensure that migrations are run and the Magneto cache is cleared as part of the deploy. Test the deploy to make sure that Magento works correctly on dev.

**Comment by babanesma** [comment]
@zhibek I have created a new job on jenkins to deploy tee-shop on zhibek server , but it seems there are a lot of symfony packages ( required by behat ) that require php 5.3.9 .

Please check http://ci.zhibek.com/job/Tee-Shop/4/console

**Comment by babanesma** [comment]
Composer install is running successfully , there is still a problem with migrations running due to some attribute naming wrongly .

**Comment by zhibek** [comment]
After lots of migration changes & lots of learning/experience, Magento is installing correctly on Jenkins including all migrations.

For reference, the main problems we experienced were:
- Creating config products (executed immediately as part of the migration) failed because the product attributes were not created yet (they were queued for creation with the $installer, that runs after all migrations for a module are processed). The fix was to move creating the products to a data migration (which runs after schema migration $installer is complete) and keeping the attribute creation in the schema migration).
- Creating the test category occurred too early (before the core Magento migration had created the root category). This meant the test category was given id 1 which was then overridden by the core migration. The fix was to move test category creation to a data migration (so it ran after the core migration).
